apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
  namespace: devops
type: Opaque
data:
  admin-user: "YWRtaW5EZXYwcHMK"
  admin-password: "cGFzSW5meDJ5ZGdhc2R5IzI0Lgo="
  admin-token: "SnRTRD9oTzFDeVNweGRrNzhXSnFJLzhYMjVPem54bGpnWjFwam9ubDR0Rlo1dG11eTc2Vmo1UmVQUGp1eERIMwo="