apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  namespace: devops
data:
  DOCKER_INFLUXDB_INIT_MODE: "setup"
  DOCKER_INFLUXDB_INIT_ORG: "porvenir"
  DOCKER_INFLUXDB_INIT_BUCKET: "JenkinsJobs"
  DOCKER_INFLUXDB_INIT_RETENTION: "0"